### ISSUE TITLE
Basic informasjon til TE for etablering reetablering basert på eksisterende funksjonalitet (MVP: slide/nettside)

### ISSUE THREAD

**Issue by acn-martinn** [Altinn/utbredelse#24]
- [x] Sette opp 3 timers workshop (19.01.2021), og kl 13.30-15.30 og ut dagen. 

- [x] Analyse av personvern

- [x] Databehandleravtalen

- [x] Schrems 2

- [x] DPIA

**Comment by acn-martinn** [comment]
"For dummies versjoner"

**Comment by lvbachmann** [comment]
@acn-martinn Her var det veldig mange avkrysningsbokser åpne for å være noe som ligger i Review/QA. Tar du en gjennomgang på hva vi mener vi har kontroll på?

**Comment by acn-martinn** [comment]
> @acn-martinn Her var det veldig mange avkrysningsbokser åpne for å være noe som ligger i Review/QA. Tar du en gjennomgang på hva vi mener vi har kontroll på?

Da har jeg tatt en liten gjennomgang og flyttet oppgaver knyttet til beta.altinn.studio til et annet issue vi har i backloggen: "Etablere produktsider og guider på altinn.studio (evt. beta.altinn.studio) #14"

**Comment by acn-martinn** [comment]
Ferdig versjon ligger i "Team Tjenestestøtte\03 Presentasjoner"
