### ISSUE TITLE
Tjenestekriterier for mulighetsbasert vekst (Tilgjengelig funksjonalitet)

### ISSUE THREAD

**Issue by acn-martinn** [Altinn/utbredelse#30]
- [ ] Oppdatere, sentralisere dokumentasjon for tjenestekriterier for vurdering av mulighetsbasert vekst
- [ ] Identifisere eksisterende tjeneste med signering for pilot
- [ ] Hvilke tjenester kan settes i gang uten hjelp fra produktteamet?
- ~~Hva er egentlig en god pilot?~~
- [ ] Ytelse, kapasitet, latency, volum mv., funksjonelle v. ikke-funksjonelle krav

**Comment by acn-martinn** [comment]
- [ ] Hvilke tjenester kan settes i gang uten hjelp fra produktteamet?
- [ ] Hva er egentlig en god pilot?
- [ ] Ytelse, kapasitet, latency, volum mv.

**Comment by lvbachmann** [comment]
@acn-martinn Er dokumentasjon av tjenestekriteriene påbegynt noe sted?
