### ISSUE TITLE
Gjennomføre Arbeidsmøte 28. januar 2021 om utbredelsesstategien

### ISSUE THREAD

**Issue by kristoffervp** [Altinn/utbredelse#4]
- [x] Presentasjon;
- [ ] Gjennomføre møtet;

- [x] Dele underlag via Altinn Sekretæriatet;

- [x] Oppdatere agenda via Altinn Sekretæriatet

**Comment by lvbachmann** [comment]
Beslutninger fra møte mellom @elwal og meg:
* Vi gjenbruker presentasjon fra @lvbachmann brukt internt (med små justeringer for å hente inn poeng fra Vidars tidligere gjennomganger)
* Vi sender ikke ut nytt underlag, men henviser til det som ble sendt ut i november (og sier at vi kan sende på nytt til de som ønsker det)
* Møtet justeres til å bli 2 timer:
  * Time 1: Gjennomgang
  * Time 2: Spørsmål/innspill
* @elwal lager justert agenda og sørger for utsending. Denne inneholder info om at de som har fått gjennomgang tidligere kan droppe time 1, og de som ikke har spørsmål/innspill kan droppe time 2.
