### ISSUE TITLE
Oppdatere https://www.altinndigital.no/altinn-studio/ med ny informasjon (pr. nå er informasjon oppdatert mai 2020)

### ISSUE THREAD

**Issue by acn-martinn** [Altinn/utbredelse#47]
![2021-01-19 13_44_14-Altinn digitalisering.png](https://images.zenhubusercontent.com/5ff6f4495f4231e51d8f86a8/b9d887d3-a070-4029-8094-118e6a53840c)

**Comment by lvbachmann** [comment]
Erstattes med lenke til #44

**Comment by lvbachmann** [comment]
Endring utført.
