### ISSUE TITLE
Utarbeide saksgrunnlag til sluttbehandling

### ISSUE THREAD

**Issue by acn-martinn** [Altinn/utbredelse#71]
- [x] Lage førsteutkast saksgrunnlag
- [x] QA av saksgrunnlag med prosjekteier
- [x] Lage presentasjon til møtene //01.03.21
- [x] Gjennomføre møte i Arbeidsutvalget //04.03.21
- [x] Gjennomføre årsmøte //18.03.21

**Comment by lvbachmann** [comment]
Oppdaget at denne også inneholdt møtegjennomføring. Gjenåpnet derfor.

**Comment by kristoffervp** [comment]
Samme saksunderlagt til Styringsrådet

**Comment by lvbachmann** [comment]
Ferdig presentert for styringsrådet - godkjent.
